import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, Github, LockKeyhole, Mail, UserRound } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Brand } from '../components/Brand'
import type { Page } from '../types'

export function LoginPage({ onNavigate }: { onNavigate: (page: Page) => void }) {
  const [show, setShow] = useState(false)
  const submit = (event: FormEvent) => { event.preventDefault(); onNavigate('overview') }
  return <AuthShell><div className="auth-card"><Brand /><div className="auth-card__heading"><h1>Welcome back</h1><p>Sign in to continue to your compliance workspace.</p></div><form onSubmit={submit}><label>Email address<span className="input-shell"><Mail size={18} /><input type="email" placeholder="name@company.com" required /></span></label><label><span className="label-row">Password<button type="button">Forgot password?</button></span><span className="input-shell"><LockKeyhole size={18} /><input type={show ? 'text' : 'password'} placeholder="••••••••" required /><button type="button" onClick={() => setShow(!show)} aria-label="Show password">{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></span></label><button className="primary-button auth-submit" type="submit">Sign in <ArrowRight size={17} /></button></form><div className="auth-divider"><span>or continue with</span></div><div className="social-row"><button><GoogleIcon />Google</button><button><Github size={18} />GitHub</button></div><p className="auth-switch">New to Stratum? <button onClick={() => onNavigate('signup')}>Create an account</button></p></div></AuthShell>
}

export function SignupPage({ onNavigate }: { onNavigate: (page: Page) => void }) {
  const [agreed, setAgreed] = useState(false)
  const submit = (event: FormEvent) => { event.preventDefault(); if (agreed) onNavigate('overview') }
  return <AuthShell><div className="auth-brand"><Brand /><h1>Build a stronger compliance posture.</h1><p>Turn regulatory complexity into clear, actionable intelligence for your entire team.</p><ul><li><Check size={16} />Continuous regulatory monitoring</li><li><Check size={16} />AI-assisted policy analysis</li><li><Check size={16} />Evidence-ready reporting</li></ul></div><div className="auth-card auth-card--signup"><button className="back-button" onClick={() => onNavigate('login')}><ArrowLeft size={16} /> Back to sign in</button><div className="auth-card__heading"><h1>Create your account</h1><p>Start your Stratum workspace in a few steps.</p></div><form onSubmit={submit}><label>Full name<span className="input-shell"><UserRound size={18} /><input placeholder="Enter your full name" required /></span></label><label>Email address<span className="input-shell"><Mail size={18} /><input type="email" placeholder="name@company.com" required /></span></label><label>Password<span className="input-shell"><LockKeyhole size={18} /><input type="password" placeholder="At least 8 characters" required minLength={8} /></span></label><label className="checkbox-row"><input type="checkbox" checked={agreed} onChange={(event) => setAgreed(event.target.checked)} /><span>I agree to the <button type="button">Terms</button> and <button type="button">Privacy Policy</button>.</span></label><button className="primary-button auth-submit" type="submit" disabled={!agreed}>Create workspace <ArrowRight size={17} /></button></form><div className="auth-divider"><span>or sign up with</span></div><div className="social-row"><button><GoogleIcon />Google</button><button><Github size={18} />GitHub</button></div></div></AuthShell>
}

export function LogoutPage({ onNavigate }: { onNavigate: (page: Page) => void }) {
  return <AuthShell simple><div className="logout-card"><Brand /><span className="logout-icon"><Check size={26} /></span><h1>You’re safely signed out.</h1><p>Your Stratum session has ended. We’ll keep monitoring your compliance landscape while you’re away.</p><button className="primary-button" onClick={() => onNavigate('login')}>Return to sign in</button><button className="text-button" onClick={() => onNavigate('overview')}><ArrowLeft size={15} /> Back to workspace preview</button><small>Protected by enterprise-grade encryption</small></div></AuthShell>
}

function AuthShell({ children, simple = false }: { children: React.ReactNode; simple?: boolean }) {
  return <main className={`auth-shell ${simple ? 'auth-shell--simple' : ''}`}><div className="auth-atmosphere auth-atmosphere--one" /><div className="auth-atmosphere auth-atmosphere--two" />{children}<footer><span>© 2026 Stratum</span><div><button>Privacy</button><button>Security</button></div></footer></main>
}

function GoogleIcon() { return <svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M21.6 12.23c0-.71-.06-1.4-.18-2.07H12v3.91h5.38a4.6 4.6 0 0 1-2 3.02v2.54h3.24c1.9-1.75 2.98-4.33 2.98-7.4Z"/><path fill="currentColor" opacity=".75" d="M12 22c2.7 0 4.98-.9 6.64-2.42l-3.24-2.54c-.9.6-2.05.96-3.4.96-2.61 0-4.82-1.76-5.61-4.13H3.04v2.62A10 10 0 0 0 12 22Z"/><path fill="currentColor" opacity=".55" d="M6.39 13.87A6 6 0 0 1 6.07 12c0-.65.11-1.28.32-1.87V7.51H3.04A10 10 0 0 0 2 12c0 1.61.39 3.13 1.04 4.49l3.35-2.62Z"/><path fill="currentColor" opacity=".9" d="M12 6c1.47 0 2.8.51 3.84 1.51l2.88-2.88A9.66 9.66 0 0 0 12 2a10 10 0 0 0-8.96 5.51l3.35 2.62C7.18 7.76 9.39 6 12 6Z"/></svg> }
